version: '3.9'

services:
  django:
    container_name: viaji_app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./viaji:/viaji
    env_file:
      - ./dotenv_files/.env

    depends_on:
      - postgres
    command: sh -c "python manage.py makemigrations && 
            python manage.py migrate &&
            python manage.py createsuperuser --noinput &&
            python manage.py runserver 0.0.0.0:8000"
 
  postgres:
    container_name: viaji_db
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/db
    env_file:
      - ./dotenv_files/.env
    ports:
      - "5432:5432"